# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build CI

on:
  push:

permissions:
  contents: read

jobs:
  build:
    name: Build (Node ${{ matrix.node.name }})
    strategy:
      fail-fast: false
      matrix:
        node:
          - version: lts/*
            name: LTS
          - version: lts/-1
            name: Previous LTS
          - version: current
            name: Current
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0

      - name: Set up Node.js environment
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: ${{ matrix.node.version }}
          cache: npm

      - name: Install dependencies and run tests
        run: npm cit
