name: Publish Package

on:
  push:
    tags:
      - '**'

permissions:
  contents: read

jobs:
  publish:
    name: Publish package to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      
      - name: Set up Node.js environment
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
