name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish package to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      
      - name: Set up Node.js environment
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3.3.0
        with:
          registry-url: https://registry.npmjs.org/
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
